name: Run Python Script

on:
  schedule:
    - cron: '0 */6 * * *'  # Runs the workflow every 6 hours
  workflow_dispatch:     # Allows manual triggering of the workflow

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.5'  # Specify your Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create config directory
      run: mkdir -p config

    - name: Set up Firebase credentials
      run: |
        echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" > config/activationKey.json
        ls -l config/activationKey.json
        cat config/activationKey.json | head -n 10  # Print the first 10 lines for debugging

    - name: Run the script
      run: python main.py
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
